package HelloApp;


/**
* HelloApp/HelloPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Wednesday, September 25, 2019 4:04:40 PM CEST
*/

public abstract class HelloPOA extends org.omg.PortableServer.Servant
 implements HelloApp.HelloOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sayHello", new java.lang.Integer (0));
    _methods.put ("sayHelp", new java.lang.Integer (1));
    _methods.put ("getTimesPlayedByUser", new java.lang.Integer (2));
    _methods.put ("getTimesPlayed", new java.lang.Integer (3));
    _methods.put ("getTopThreeUsersBySong", new java.lang.Integer (4));
    _methods.put ("getTopThreeSongsByUser", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // HelloApp/Hello/sayHello
       {
         String message = in.read_string ();
         String $result = null;
         $result = this.sayHello (message);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // HelloApp/Hello/sayHelp
       {
         String help = in.read_string ();
         String $result = null;
         $result = this.sayHelp (help);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // HelloApp/Hello/getTimesPlayedByUser
       {
         String user = in.read_string ();
         String song = in.read_string ();
         int $result = (int)0;
         $result = this.getTimesPlayedByUser (user, song);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // HelloApp/Hello/getTimesPlayed
       {
         String song = in.read_string ();
         int $result = (int)0;
         $result = this.getTimesPlayed (song);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // HelloApp/Hello/getTopThreeUsersBySong
       {
         String song = in.read_string ();
         HelloApp.TopThreeUsers $result = null;
         $result = this.getTopThreeUsersBySong (song);
         out = $rh.createReply();
         HelloApp.TopThreeUsersHelper.write (out, $result);
         break;
       }

       case 5:  // HelloApp/Hello/getTopThreeSongsByUser
       {
         String user = in.read_string ();
         HelloApp.TopThreeSongs $result = null;
         $result = this.getTopThreeSongsByUser (user);
         out = $rh.createReply();
         HelloApp.TopThreeSongsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:HelloApp/Hello:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Hello _this() 
  {
    return HelloHelper.narrow(
    super._this_object());
  }

  public Hello _this(org.omg.CORBA.ORB orb) 
  {
    return HelloHelper.narrow(
    super._this_object(orb));
  }


} // class HelloPOA
