package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Wednesday, September 25, 2019 4:04:40 PM CEST
*/

public interface HelloOperations 
{
  String sayHello (String message);
  String sayHelp (String help);
  int getTimesPlayedByUser (String user, String song);
  int getTimesPlayed (String song);
  HelloApp.TopThreeUsers getTopThreeUsersBySong (String song);
  HelloApp.TopThreeSongs getTopThreeSongsByUser (String user);
} // interface HelloOperations
