package HelloApp;


/**
* HelloApp/SongCounterDefaultFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Wednesday, September 25, 2019 4:04:40 PM CEST
*/

public class SongCounterDefaultFactory implements org.omg.CORBA.portable.ValueFactory {

  public java.io.Serializable read_value (org.omg.CORBA_2_3.portable.InputStream is)
  {
    return is.read_value(new SongCounterImpl ());
  }
}
