package HelloApp;

/**
* HelloApp/SongProfileHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, September 23, 2019 1:50:32 PM CEST
*/

public final class SongProfileHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.SongProfile value = null;

  public SongProfileHolder ()
  {
  }

  public SongProfileHolder (HelloApp.SongProfile initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.SongProfileHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.SongProfileHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.SongProfileHelper.type ();
  }

}
