package HelloApp;

/**
* HelloApp/SongCounterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Wednesday, September 25, 2019 4:04:40 PM CEST
*/

public final class SongCounterHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.SongCounter value = null;

  public SongCounterHolder ()
  {
  }

  public SongCounterHolder (HelloApp.SongCounter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.SongCounterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.SongCounterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.SongCounterHelper.type ();
  }

}
