package HelloApp;


/**
* HelloApp/SongProfileDefaultFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, September 23, 2019 1:50:32 PM CEST
*/

public class SongProfileDefaultFactory implements org.omg.CORBA.portable.ValueFactory {

  public java.io.Serializable read_value (org.omg.CORBA_2_3.portable.InputStream is)
  {
    return is.read_value(new SongProfileImpl ());
  }
}
