package HelloApp;

/**
* HelloApp/TopThreeSongsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Wednesday, September 25, 2019 4:04:40 PM CEST
*/

public final class TopThreeSongsHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.TopThreeSongs value = null;

  public TopThreeSongsHolder ()
  {
  }

  public TopThreeSongsHolder (HelloApp.TopThreeSongs initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.TopThreeSongsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.TopThreeSongsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.TopThreeSongsHelper.type ();
  }

}
