package HelloApp;


/**
* HelloApp/TopThreeSongs.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, September 23, 2019 1:50:32 PM CEST
*/

public abstract class TopThreeSongs implements org.omg.CORBA.portable.StreamableValue
{
  public HelloApp.SongCounter topThreeSongs[] = null;

  private static String[] _truncatable_ids = {
    HelloApp.TopThreeSongsHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    int _len0 = istream.read_long ();
    this.topThreeSongs = new HelloApp.SongCounter[_len0];
    for (int _o1 = 0;_o1 < this.topThreeSongs.length; ++_o1)
      this.topThreeSongs[_o1] = HelloApp.SongCounterHelper.read (istream);
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    ostream.write_long (this.topThreeSongs.length);
    for (int _i0 = 0;_i0 < this.topThreeSongs.length; ++_i0)
      HelloApp.SongCounterHelper.write (ostream, this.topThreeSongs[_i0]);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.TopThreeSongsHelper.type ();
  }
} // class TopThreeSongs
