package HelloApp;

/**
* HelloApp/TopThreeUsersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, September 23, 2019 1:50:32 PM CEST
*/

public final class TopThreeUsersHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.TopThreeUsers value = null;

  public TopThreeUsersHolder ()
  {
  }

  public TopThreeUsersHolder (HelloApp.TopThreeUsers initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.TopThreeUsersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.TopThreeUsersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.TopThreeUsersHelper.type ();
  }

}
