package HelloApp;

/**
* HelloApp/UserCounterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Wednesday, September 25, 2019 4:04:40 PM CEST
*/

public final class UserCounterHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.UserCounter value = null;

  public UserCounterHolder ()
  {
  }

  public UserCounterHolder (HelloApp.UserCounter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.UserCounterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.UserCounterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.UserCounterHelper.type ();
  }

}
